---
kind: pipeline
type: exec
name: sysinfo

platform:
  os: linux
  arch: amd64

steps:
- name: run tests
  commands:
    - make test

- name: build
  commands:
    - make build

- name: build and push image
  environment:
    BUILDKIT:
      from_secret: buildkit
  commands:
    - vab build -r $IMAGE -p .
  when:
    event:
      - promote
    target:
      - production
    status:
      - success
