---
kind: pipeline
type: exec
name: apps/sysinfo

platform:
  os: linux
  arch: amd64

steps:
- name: run tests
  commands:
    - make test

- name: build
  commands:
    - make build

- name: build and push image
  environment:
    BUILDKIT:
      from_secret: buildkit
    IMAGE:
      from_secret: image
  commands:
    - vab build -r $IMAGE -p .
  when:
    status:
      - success
